[supervisord]
nodaemon=true
user=root
pidfile=/var/run/supervisord.pid
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
user=root
priority=100

[program:dotnet-api]
command=dotnet /app/backend/MealieApi.WebApi.dll
directory=/app/backend
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
user=mealie
environment=ASPNETCORE_ENVIRONMENT=Production,ASPNETCORE_URLS="http://127.0.0.1:5000"
priority=200
